### ISSUE TITLE
All blocks drops additionals items in overworld

### ISSUE THREAD

**Issue by Xen0Xys** [ULTUX/StoneDropPlugin#54]
Version: 1.16.5
Error I get:
```
>.... [20:53:24 WARN]: [StoneDrop] Task #1210566 for StoneDrop v1.9.8 generated an exception
java.lang.NullPointerException: null
at me.apisek12.StoneDrop.EventListeners.BlockBreakEventListener.lambda$InventoryCloseEvent$7(BlockBreakEventListener.java:348) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[paper-1.16.5-440.jar:git-Paper-"0514fc4e2"]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[paper-1.16.5-440.jar:git-Paper-"0514fc4e2"]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[paper-1.16.5-440.jar:git-Paper-"0514fc4e2"]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[paper-1.16.5-440.jar:git-Paper-"0514fc4e2"]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[paper-1.16.5-440.jar:git-Paper-"0514fc4e2"]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[paper-1.16.5-440.jar:git-Paper-"0514fc4e2"]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[paper-1.16.5-440.jar:git-Paper-"0514fc4e2"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```
My configuration:
```yaml
#These are chances of drop from STONE
chances:
  COAL:
    fortune-0:
      chance: 0.02
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.021
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.022
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.023
      max-amount: 4
      min-amount: 3
  DIAMOND:
    minLevel: 0
    maxLevel: 25
    fortune-0:
      chance: 0.0025
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.0027
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.003
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.00325
      max-amount: 4
      min-amount: 3
  EMERALD:
    fortune-0:
      chance: 0.0025
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.0025
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.003
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.0035
      max-amount: 4
      min-amount: 3
  GOLD_INGOT:
    fortune-0:
      chance: 0.008
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.009
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.01
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.015
      max-amount: 4
      min-amount: 3
  IRON_INGOT:
    fortune-0:
      chance: 0.015
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.015
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.02
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.02
      max-amount: 4
      min-amount: 3
  LAPIS_LAZULI:
    fortune-0:
      chance: 0.005
      max-amount: 3
      min-amount: 2
    fortune-1:
      chance: 0.008
      max-amount: 4
      min-amount: 3
    fortine-2:
      chance: 0.01
      max-amount: 5
      min-amount: 4
    fortune-3:
      chance: 0.015
      max-amount: 6
      min-amount: 5
  REDSTONE:
    fortune-0:
      chance: 0.005
      max-amount: 3
      min-amount: 2
    fortune-1:
      chance: 0.007
      max-amount: 4
      min-amount: 3
    fortune-2:
      chance: 0.009
      max-amount: 5
      min-amount: 4
    fortune-3:
      chance: 0.01
      max-amount: 6
      min-amount: 5
  BLUE_ICE:
    fortune-0:
      chance: 0.05
      max-amount: 3
      min-amount: 2
    fortune-1:
      chance: 0.052
      max-amount: 4
      min-amount: 3
    fortune-2:
      chance: 0.054
      max-amount: 5
      min-amount: 4
    fortune-3:
      chance: 0.056
      max-amount: 6
      min-amount: 5

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#This is chance of getting a chest spawned
chest-spawn-chance: 5.0E-4

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#And these are possible contents of the chest
chest:
  DIAMOND:
    chance: 0.8
    min: 1
    max: 20
  IRON_INGOT:
    chance: 0.8
    min: 5
    max: 48
  GOLD_INGOT:
    chance: 0.75
    min: 1
    max: 40
  ENCHANTED_GOLDEN_APPLE:
    chance: 0.3
    min: 1
    max: 1
  SADDLE:
    chance: 0.1
    min: 1
    max: 1
  GOLDEN_CARROT:
    chance: 1.0
    min: 5
    max: 40
  TOTEM_OF_UNDYING:
    chance: 0.02
    min: 1
    max: 1
  BLUE_ICE:
    chance: 1.0
    min: 32
    max: 64
  DIAMOND_PICKAXE:
    chance: 0.1
    min: 1
    max: 1
    enchant:
      mending: 1
  FISHING_ROD:
    chance: 0.1
    min: 1
    max: 1
    enchant:
      unbreaking: 3
      lure: 3
      luck_of_the_sea: 3
      mending: 1

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#List of blocks that the plugin should work on. The list of all possible blocks is listed here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
dropBlocks:
  - STONE
#  - ANDESITE
#  - GRANITE

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#experience dropped from stone:
experience: 1.0

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#put here all world that you would like to have disabled:
disabled-worlds: [world_nether, world_the_end]

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#Should ores drop items
ore-drop: true
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Should the items ne dropped directly into the inventory
drop-to-inventory: false
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Should display "The plugin has been updated" message
display-update-message: true
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Should exp be added to player stats or dropped as exp orb - WARNING: in that case experience value has to be >= 1.0
drop-exp-orb: true

```
